// eslint-disable-next-line
export default [
	{
		id: 1,
		title: "Încercare",
		credits: "20 Credite",
		price: "49 €",
		desc: "Poate fi cumpărat doar o singură dată și se pot cumpăra până la 20 de imagini",
		btnText: "Cumpără",
		btnUrl: "/cart",
	},
	{
		id: 2,
		title: "Small",
		credits: "20 Credite",
		price: "99 €",
		desc: "Pentru utilizatori obișnuiți și se pot cumpăra până la 20 de imagini.",
		btnText: "Cumpără",
		btnUrl: "/cart",
	},
	{
		id: 3,
		title: "Medium",
		credits: "70 Credite",
		price: "299 €",
		desc: "Pentru utilizatori obișnuiți și se pot cumpăra până la 70 de imagini.",
		btnText: "Cumpără",
		btnUrl: "/cart",
	},
	{
		id: 4,
		title: "Large",
		credits: "260 Credite",
		price: "999 €",
		desc: "Pentru profesioniști și se pot cumpăra până la 260 de imagini.",
		btnText: "Cumpără",
		btnUrl: "/cart",
	},
	{
		id: 5,
		title: "Extra Large",
		credits: "1000 Credite",
		price: "2999 €",
		desc: "Cea mai avantajoasă opțiune, se pot cumpăra până la 1000 de imagini.",
		btnText: "Cumpără",
		btnUrl: "/cart",
	},
	{
		id: 6,
		title: "Custom",
		credits: "Enterprise",
		desc: "Beneficiați de prețuri și servicii personalizate, incluzând căutarea de imagini, suport telefonic dedicat etc.",
		btnText: "Contactează-ne",
		btnUrl: "/contact",
	},
];
