// eslint-disable-next-line
export default [
	{
		id: 1,
		title: "Rights Managed",
		subtitle: "Web",
		price: 19,
		resolution: "High",
		license: "Editorial",
		distribution: "Doar Internet",
		multiSeat: "Nu",
	},
	{
		id: 2,
		title: "Rights Managed",
		subtitle: "Internet și Print",
		price: 99,
		resolution: "High",
		license: "Editorial",
		distribution: "Nelimitat",
		multiSeat: "Nu",
	},
	{
		id: 3,
		title: "Royalty Free Classic",
		subtitle: "Web",
		price: 9,
		resolution: "Medium",
		license: "Editorial și Comercial",
		distribution: "Doar Internet",
		multiSeat: "Nu",
	},
	{
		id: 4,
		title: "Royalty Free Classic",
		subtitle: "Full Royalty Free",
		price: 99,
		resolution: "High",
		license: "Editorial și Comercial",
		distribution: "Nelimitat",
		multiSeat: "Da",
	},
	{
		id: 5,
		title: "Royalty Free Premium",
		subtitle: "Web",
		price: 99,
		resolution: "Medium",
		license: "Editorial și Comercial",
		distribution: "Doar Internet",
		multiSeat: "Da",
	},
	{
		id: 1,
		title: "Royalty Free Premium",
		subtitle: "Full Royalty Free",
		price: 349,
		resolution: "High",
		license: "Editorial și Comercial",
		distribution: "Nelimitat",
		multiSeat: "Da",
	},
];
